// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package example

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_kCreateRoomRequest    MessageType = 0
	MessageType_kCreateRoomResponse   MessageType = 1
	MessageType_kJoinRoomRequest      MessageType = 2
	MessageType_kJoinRoomResponse     MessageType = 3
	MessageType_kSendMessageRequest   MessageType = 4
	MessageType_kSendMessageResponse  MessageType = 5
	MessageType_kCreateRoomNotify     MessageType = 101
	MessageType_kCreateJoinRoomNotify MessageType = 102
	MessageType_kSendMessageNotify    MessageType = 103
)

var MessageType_name = map[int32]string{
	0:   "kCreateRoomRequest",
	1:   "kCreateRoomResponse",
	2:   "kJoinRoomRequest",
	3:   "kJoinRoomResponse",
	4:   "kSendMessageRequest",
	5:   "kSendMessageResponse",
	101: "kCreateRoomNotify",
	102: "kCreateJoinRoomNotify",
	103: "kSendMessageNotify",
}

var MessageType_value = map[string]int32{
	"kCreateRoomRequest":    0,
	"kCreateRoomResponse":   1,
	"kJoinRoomRequest":      2,
	"kJoinRoomResponse":     3,
	"kSendMessageRequest":   4,
	"kSendMessageResponse":  5,
	"kCreateRoomNotify":     101,
	"kCreateJoinRoomNotify": 102,
	"kSendMessageNotify":    103,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type JoinRoomRequest struct {
	MessageType          MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=example.MessageType" json:"messageType,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *JoinRoomRequest) Reset()         { *m = JoinRoomRequest{} }
func (m *JoinRoomRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRoomRequest) ProtoMessage()    {}
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *JoinRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomRequest.Unmarshal(m, b)
}
func (m *JoinRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomRequest.Marshal(b, m, deterministic)
}
func (m *JoinRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomRequest.Merge(m, src)
}
func (m *JoinRoomRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRoomRequest.Size(m)
}
func (m *JoinRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomRequest proto.InternalMessageInfo

func (m *JoinRoomRequest) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_kCreateRoomRequest
}

func (m *JoinRoomRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type JoinRoomResponse struct {
	MessageType          MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=example.MessageType" json:"messageType,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsSuccess            bool        `protobuf:"varint,3,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *JoinRoomResponse) Reset()         { *m = JoinRoomResponse{} }
func (m *JoinRoomResponse) String() string { return proto.CompactTextString(m) }
func (*JoinRoomResponse) ProtoMessage()    {}
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *JoinRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomResponse.Unmarshal(m, b)
}
func (m *JoinRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomResponse.Marshal(b, m, deterministic)
}
func (m *JoinRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomResponse.Merge(m, src)
}
func (m *JoinRoomResponse) XXX_Size() int {
	return xxx_messageInfo_JoinRoomResponse.Size(m)
}
func (m *JoinRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomResponse proto.InternalMessageInfo

func (m *JoinRoomResponse) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_kCreateRoomRequest
}

func (m *JoinRoomResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JoinRoomResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

type SendMessageRequest struct {
	MessageType          MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=example.MessageType" json:"messageType,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Message              string      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SendMessageRequest) Reset()         { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()    {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *SendMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequest.Unmarshal(m, b)
}
func (m *SendMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequest.Merge(m, src)
}
func (m *SendMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequest.Size(m)
}
func (m *SendMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequest proto.InternalMessageInfo

func (m *SendMessageRequest) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_kCreateRoomRequest
}

func (m *SendMessageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SendMessageRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SendMessageNotify struct {
	MessageType          MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=example.MessageType" json:"messageType,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Message              string      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SendMessageNotify) Reset()         { *m = SendMessageNotify{} }
func (m *SendMessageNotify) String() string { return proto.CompactTextString(m) }
func (*SendMessageNotify) ProtoMessage()    {}
func (*SendMessageNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *SendMessageNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageNotify.Unmarshal(m, b)
}
func (m *SendMessageNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageNotify.Marshal(b, m, deterministic)
}
func (m *SendMessageNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageNotify.Merge(m, src)
}
func (m *SendMessageNotify) XXX_Size() int {
	return xxx_messageInfo_SendMessageNotify.Size(m)
}
func (m *SendMessageNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageNotify.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageNotify proto.InternalMessageInfo

func (m *SendMessageNotify) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_kCreateRoomRequest
}

func (m *SendMessageNotify) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SendMessageNotify) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("example.MessageType", MessageType_name, MessageType_value)
	proto.RegisterType((*JoinRoomRequest)(nil), "example.JoinRoomRequest")
	proto.RegisterType((*JoinRoomResponse)(nil), "example.JoinRoomResponse")
	proto.RegisterType((*SendMessageRequest)(nil), "example.SendMessageRequest")
	proto.RegisterType((*SendMessageNotify)(nil), "example.SendMessageNotify")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x71, 0x5b, 0x28, 0xb9, 0x0a, 0xb8, 0x1e, 0x29, 0x18, 0x89, 0x21, 0xca, 0x14, 0x31,
	0x64, 0x00, 0x89, 0x17, 0x60, 0x43, 0x82, 0xc1, 0x65, 0x65, 0x08, 0xe5, 0x5a, 0x45, 0x21, 0x71,
	0xa8, 0x53, 0x89, 0x20, 0x1e, 0x98, 0xc7, 0x40, 0x72, 0x5d, 0x25, 0x6d, 0x56, 0x60, 0xb3, 0xef,
	0xcf, 0xef, 0xd3, 0xdd, 0x77, 0x70, 0x94, 0xb3, 0x31, 0xc9, 0x82, 0xe3, 0x72, 0xa9, 0x2b, 0x4d,
	0x43, 0xfe, 0x48, 0xf2, 0xf2, 0x8d, 0xc3, 0x67, 0x38, 0xb9, 0xd7, 0x69, 0xa1, 0xb4, 0xce, 0x15,
	0xbf, 0xaf, 0xd8, 0x54, 0x74, 0x0b, 0x23, 0x57, 0xfc, 0x54, 0x97, 0x2c, 0x45, 0x20, 0xa2, 0xe3,
	0x6b, 0x3f, 0x76, 0x1d, 0xf1, 0x43, 0x93, 0x53, 0xed, 0x42, 0x22, 0x18, 0x14, 0x49, 0xce, 0xb2,
	0x17, 0x88, 0xc8, 0x53, 0xf6, 0x1d, 0x7e, 0x01, 0x36, 0x78, 0x53, 0xea, 0xc2, 0xf0, 0x6f, 0xf2,
	0xe9, 0x12, 0xbc, 0xd4, 0x4c, 0x57, 0xb3, 0x19, 0x1b, 0x23, 0xfb, 0x81, 0x88, 0x0e, 0x55, 0x13,
	0x08, 0x3f, 0x81, 0xa6, 0x5c, 0xbc, 0x3a, 0xe2, 0x1f, 0xcc, 0x47, 0x12, 0x86, 0xae, 0xc4, 0xaa,
	0x7b, 0x6a, 0xf3, 0x0d, 0x6b, 0x18, 0xb7, 0xb4, 0x1f, 0x75, 0x95, 0xce, 0xeb, 0xff, 0x91, 0xbe,
	0xfa, 0x16, 0x30, 0x6a, 0xa1, 0xe8, 0x0c, 0x28, 0xbb, 0x5b, 0x72, 0x52, 0x71, 0xcb, 0x66, 0xdc,
	0xa3, 0x73, 0x38, 0xdd, 0x8a, 0xaf, 0xfd, 0x41, 0x41, 0x3e, 0x60, 0xb6, 0x73, 0x15, 0xd8, 0xa3,
	0x09, 0x8c, 0xb3, 0x5d, 0x33, 0xb1, 0x6f, 0x29, 0xdd, 0x2d, 0xe3, 0x80, 0x24, 0xf8, 0xdb, 0x09,
	0xd7, 0xb2, 0x6f, 0x49, 0x8d, 0xf0, 0x7a, 0x37, 0xc8, 0x74, 0x01, 0x13, 0x17, 0xde, 0xc8, 0xb8,
	0xd4, 0xdc, 0x8e, 0xd0, 0x59, 0x27, 0x2e, 0x5e, 0x0e, 0xec, 0x39, 0xdf, 0xfc, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x98, 0xf3, 0xaa, 0xd2, 0xdf, 0x02, 0x00, 0x00,
}
