// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package protomessage

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	MessageType_kCreateNicknameRequest  MessageType = 0
	MessageType_kCreateNicknameResponse MessageType = 1
	MessageType_kCreateRoomRequest      MessageType = 2
	MessageType_kCreateRoomResponse     MessageType = 3
	MessageType_kJoinRoomRequest        MessageType = 4
	MessageType_kJoinRoomResponse       MessageType = 5
	MessageType_kSendMessageRequest     MessageType = 6
	MessageType_kSendMessageResponse    MessageType = 7
	MessageType_kCreateRoomNotify       MessageType = 101
	MessageType_kCreateJoinRoomNotify   MessageType = 102
	MessageType_kSendMessageNotify      MessageType = 103
)

var MessageType_name = map[int32]string{
	0:   "kCreateNicknameRequest",
	1:   "kCreateNicknameResponse",
	2:   "kCreateRoomRequest",
	3:   "kCreateRoomResponse",
	4:   "kJoinRoomRequest",
	5:   "kJoinRoomResponse",
	6:   "kSendMessageRequest",
	7:   "kSendMessageResponse",
	101: "kCreateRoomNotify",
	102: "kCreateJoinRoomNotify",
	103: "kSendMessageNotify",
}

var MessageType_value = map[string]int32{
	"kCreateNicknameRequest":  0,
	"kCreateNicknameResponse": 1,
	"kCreateRoomRequest":      2,
	"kCreateRoomResponse":     3,
	"kJoinRoomRequest":        4,
	"kJoinRoomResponse":       5,
	"kSendMessageRequest":     6,
	"kSendMessageResponse":    7,
	"kCreateRoomNotify":       101,
	"kCreateJoinRoomNotify":   102,
	"kSendMessageNotify":      103,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type CreateNicknameRequest struct {
	MessageType          MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=protomessage.MessageType" json:"messageType,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateNicknameRequest) Reset()         { *m = CreateNicknameRequest{} }
func (m *CreateNicknameRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNicknameRequest) ProtoMessage()    {}
func (*CreateNicknameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *CreateNicknameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNicknameRequest.Unmarshal(m, b)
}
func (m *CreateNicknameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNicknameRequest.Marshal(b, m, deterministic)
}
func (m *CreateNicknameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNicknameRequest.Merge(m, src)
}
func (m *CreateNicknameRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNicknameRequest.Size(m)
}
func (m *CreateNicknameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNicknameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNicknameRequest proto.InternalMessageInfo

func (m *CreateNicknameRequest) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_kCreateNicknameRequest
}

func (m *CreateNicknameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateNicknameResponse struct {
	MessageType          MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=protomessage.MessageType" json:"messageType,omitempty"`
	UserId               uint32      `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Name                 string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateNicknameResponse) Reset()         { *m = CreateNicknameResponse{} }
func (m *CreateNicknameResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNicknameResponse) ProtoMessage()    {}
func (*CreateNicknameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *CreateNicknameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNicknameResponse.Unmarshal(m, b)
}
func (m *CreateNicknameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNicknameResponse.Marshal(b, m, deterministic)
}
func (m *CreateNicknameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNicknameResponse.Merge(m, src)
}
func (m *CreateNicknameResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNicknameResponse.Size(m)
}
func (m *CreateNicknameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNicknameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNicknameResponse proto.InternalMessageInfo

func (m *CreateNicknameResponse) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_kCreateNicknameRequest
}

func (m *CreateNicknameResponse) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CreateNicknameResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateRoomRequest struct {
	MessageType          MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=protomessage.MessageType" json:"messageType,omitempty"`
	RoomId               uint32      `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Name                 string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateRoomRequest) Reset()         { *m = CreateRoomRequest{} }
func (m *CreateRoomRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoomRequest) ProtoMessage()    {}
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *CreateRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomRequest.Unmarshal(m, b)
}
func (m *CreateRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomRequest.Marshal(b, m, deterministic)
}
func (m *CreateRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomRequest.Merge(m, src)
}
func (m *CreateRoomRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoomRequest.Size(m)
}
func (m *CreateRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomRequest proto.InternalMessageInfo

func (m *CreateRoomRequest) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_kCreateNicknameRequest
}

func (m *CreateRoomRequest) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *CreateRoomRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateRoomResponse struct {
	MessageType          MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=protomessage.MessageType" json:"messageType,omitempty"`
	RoomId               uint32      `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Name                 string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateRoomResponse) Reset()         { *m = CreateRoomResponse{} }
func (m *CreateRoomResponse) String() string { return proto.CompactTextString(m) }
func (*CreateRoomResponse) ProtoMessage()    {}
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *CreateRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomResponse.Unmarshal(m, b)
}
func (m *CreateRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomResponse.Marshal(b, m, deterministic)
}
func (m *CreateRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomResponse.Merge(m, src)
}
func (m *CreateRoomResponse) XXX_Size() int {
	return xxx_messageInfo_CreateRoomResponse.Size(m)
}
func (m *CreateRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomResponse proto.InternalMessageInfo

func (m *CreateRoomResponse) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_kCreateNicknameRequest
}

func (m *CreateRoomResponse) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *CreateRoomResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type JoinRoomRequest struct {
	MessageType          MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=protomessage.MessageType" json:"messageType,omitempty"`
	RoomId               uint32      `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId               uint32      `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Name                 string      `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *JoinRoomRequest) Reset()         { *m = JoinRoomRequest{} }
func (m *JoinRoomRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRoomRequest) ProtoMessage()    {}
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *JoinRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomRequest.Unmarshal(m, b)
}
func (m *JoinRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomRequest.Marshal(b, m, deterministic)
}
func (m *JoinRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomRequest.Merge(m, src)
}
func (m *JoinRoomRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRoomRequest.Size(m)
}
func (m *JoinRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomRequest proto.InternalMessageInfo

func (m *JoinRoomRequest) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_kCreateNicknameRequest
}

func (m *JoinRoomRequest) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *JoinRoomRequest) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *JoinRoomRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type JoinRoomResponse struct {
	MessageType          MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=protomessage.MessageType" json:"messageType,omitempty"`
	RoomId               uint32      `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Name                 string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IsSuccess            bool        `protobuf:"varint,4,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *JoinRoomResponse) Reset()         { *m = JoinRoomResponse{} }
func (m *JoinRoomResponse) String() string { return proto.CompactTextString(m) }
func (*JoinRoomResponse) ProtoMessage()    {}
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *JoinRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRoomResponse.Unmarshal(m, b)
}
func (m *JoinRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRoomResponse.Marshal(b, m, deterministic)
}
func (m *JoinRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRoomResponse.Merge(m, src)
}
func (m *JoinRoomResponse) XXX_Size() int {
	return xxx_messageInfo_JoinRoomResponse.Size(m)
}
func (m *JoinRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRoomResponse proto.InternalMessageInfo

func (m *JoinRoomResponse) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_kCreateNicknameRequest
}

func (m *JoinRoomResponse) GetRoomId() uint32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *JoinRoomResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JoinRoomResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

type SendMessageRequest struct {
	MessageType          MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=protomessage.MessageType" json:"messageType,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Message              string      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SendMessageRequest) Reset()         { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()    {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *SendMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequest.Unmarshal(m, b)
}
func (m *SendMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequest.Merge(m, src)
}
func (m *SendMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequest.Size(m)
}
func (m *SendMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequest proto.InternalMessageInfo

func (m *SendMessageRequest) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_kCreateNicknameRequest
}

func (m *SendMessageRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SendMessageRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SendMessageNotify struct {
	MessageType          MessageType `protobuf:"varint,1,opt,name=messageType,proto3,enum=protomessage.MessageType" json:"messageType,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Message              string      `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SendMessageNotify) Reset()         { *m = SendMessageNotify{} }
func (m *SendMessageNotify) String() string { return proto.CompactTextString(m) }
func (*SendMessageNotify) ProtoMessage()    {}
func (*SendMessageNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *SendMessageNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageNotify.Unmarshal(m, b)
}
func (m *SendMessageNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageNotify.Marshal(b, m, deterministic)
}
func (m *SendMessageNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageNotify.Merge(m, src)
}
func (m *SendMessageNotify) XXX_Size() int {
	return xxx_messageInfo_SendMessageNotify.Size(m)
}
func (m *SendMessageNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageNotify.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageNotify proto.InternalMessageInfo

func (m *SendMessageNotify) GetMessageType() MessageType {
	if m != nil {
		return m.MessageType
	}
	return MessageType_kCreateNicknameRequest
}

func (m *SendMessageNotify) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SendMessageNotify) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("protomessage.MessageType", MessageType_name, MessageType_value)
	proto.RegisterType((*CreateNicknameRequest)(nil), "protomessage.CreateNicknameRequest")
	proto.RegisterType((*CreateNicknameResponse)(nil), "protomessage.CreateNicknameResponse")
	proto.RegisterType((*CreateRoomRequest)(nil), "protomessage.CreateRoomRequest")
	proto.RegisterType((*CreateRoomResponse)(nil), "protomessage.CreateRoomResponse")
	proto.RegisterType((*JoinRoomRequest)(nil), "protomessage.JoinRoomRequest")
	proto.RegisterType((*JoinRoomResponse)(nil), "protomessage.JoinRoomResponse")
	proto.RegisterType((*SendMessageRequest)(nil), "protomessage.SendMessageRequest")
	proto.RegisterType((*SendMessageNotify)(nil), "protomessage.SendMessageNotify")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0xbd, 0x52, 0xc2, 0x40,
	0x10, 0xc7, 0x3d, 0xc0, 0x20, 0x8b, 0xe8, 0xb1, 0x42, 0x08, 0x6a, 0xc1, 0xa4, 0x62, 0x2c, 0x28,
	0xb4, 0xb4, 0xb4, 0xd2, 0x19, 0x29, 0x82, 0x2f, 0x80, 0x70, 0x60, 0xe6, 0x26, 0x39, 0xcc, 0x85,
	0x82, 0x19, 0x3f, 0xc6, 0x57, 0xb0, 0xb3, 0xf4, 0x4d, 0x1d, 0x8f, 0xc3, 0x9c, 0x49, 0x0a, 0x67,
	0x04, 0x2a, 0xd8, 0xbd, 0xbd, 0xfd, 0xfd, 0x77, 0xf7, 0x36, 0x50, 0x0b, 0x98, 0x94, 0xc3, 0x29,
	0xeb, 0xcd, 0x22, 0x11, 0x0b, 0xdc, 0x57, 0x3f, 0xda, 0xe7, 0x3e, 0x40, 0xf3, 0x2a, 0x62, 0xc3,
	0x98, 0xf5, 0xfd, 0x11, 0x0f, 0x87, 0x01, 0xf3, 0xd8, 0xe3, 0x9c, 0xc9, 0x18, 0x2f, 0xa1, 0xaa,
	0x63, 0xee, 0x16, 0x33, 0xe6, 0x90, 0x0e, 0xe9, 0x1e, 0x9c, 0xb7, 0x7b, 0xe6, 0xe5, 0xde, 0x6d,
	0x12, 0xe0, 0x99, 0xd1, 0x88, 0x50, 0xfa, 0xce, 0xe5, 0x14, 0x3a, 0xa4, 0x5b, 0xf1, 0xd4, 0x7f,
	0xf7, 0x8d, 0x80, 0x9d, 0x46, 0xc9, 0x99, 0x08, 0x25, 0xfb, 0x1f, 0xcb, 0x06, 0x6b, 0x2e, 0x59,
	0x74, 0x3d, 0x56, 0xb4, 0x9a, 0xa7, 0xad, 0x1f, 0x0d, 0x45, 0x43, 0xc3, 0x13, 0xd4, 0x97, 0x12,
	0x3c, 0x21, 0x82, 0xb5, 0x54, 0x6a, 0x83, 0x15, 0x09, 0x11, 0x24, 0xf4, 0xa5, 0x95, 0x4b, 0x7f,
	0x06, 0x34, 0xe9, 0x6b, 0x2a, 0xfe, 0xcf, 0xf8, 0x77, 0x02, 0x87, 0x37, 0xc2, 0x0f, 0x37, 0x5e,
	0x7b, 0x32, 0x91, 0x62, 0xee, 0x44, 0x4a, 0x86, 0xa8, 0x0f, 0x02, 0x34, 0x11, 0xb5, 0xe5, 0x96,
	0xe0, 0x29, 0x54, 0x7c, 0x39, 0x98, 0x8f, 0x46, 0x4c, 0x4a, 0x25, 0x6b, 0xcf, 0x4b, 0x1c, 0xee,
	0x2b, 0xe0, 0x80, 0x85, 0x63, 0x4d, 0xda, 0xd4, 0x62, 0xa0, 0x03, 0x65, 0x1d, 0xa2, 0xb5, 0xad,
	0x4c, 0xf7, 0x05, 0xea, 0x86, 0x80, 0xbe, 0x88, 0xfd, 0xc9, 0x62, 0x8b, 0xfc, 0xb3, 0xcf, 0x02,
	0x54, 0x8d, 0x54, 0x78, 0x0c, 0x36, 0xcf, 0xfd, 0x5a, 0xd0, 0x1d, 0x3c, 0x81, 0x16, 0xcf, 0x5f,
	0x6f, 0x4a, 0xd0, 0x06, 0xe4, 0x99, 0xc5, 0xa3, 0x05, 0x6c, 0xc1, 0x11, 0xcf, 0xae, 0x04, 0x2d,
	0x62, 0x03, 0x28, 0x4f, 0xbd, 0x55, 0x5a, 0xc2, 0x26, 0xd4, 0x79, 0xfa, 0xb1, 0xd0, 0x5d, 0x95,
	0x25, 0x3b, 0x28, 0x6a, 0xa1, 0x03, 0x8d, 0xdf, 0x07, 0xfa, 0x4a, 0x59, 0x65, 0x4a, 0xc0, 0xcb,
	0xce, 0x52, 0x86, 0x6d, 0x68, 0x6a, 0xf7, 0x0a, 0xa3, 0x8f, 0x26, 0xaa, 0x84, 0xcc, 0x30, 0xe8,
	0xf4, 0xde, 0x52, 0x8d, 0xbf, 0xf8, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x81, 0x47, 0x93, 0x13, 0x66,
	0x05, 0x00, 0x00,
}
